name: Semantic Pull Requests
on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@ad47c64a77f00b53fe0a6b41d9a65f14c2e0b5fd
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          validateSingleCommit: true
