name: Semantic Pull Requests
on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          validateSingleCommit: true
