name: Setup
on:
  workflow_call:

jobs:
  initialise_environments:
    runs-on: basic-platform
    steps:
      - name: Trigger initial update environments
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Update Environments
          token: ${{ secrets.GIT_TOKEN }}

  setup_sonarqube:
    runs-on: basic-platform
    steps:
      - name: SonarQube Create Project
        run: |
          curl -s -S -X POST -u "${{ secrets.SONAR_TOKEN }}:" "${{ secrets.SONAR_HOST_URL }}/api/projects/create" -d "name=${{ github.event.repository.name }}&project=${{ github.event.repository.name }}"

      - name: SonarQube Update Default Branch
        run: |
          curl -s -S -X POST -u "${{ secrets.SONAR_TOKEN }}:" "${{ secrets.SONAR_HOST_URL }}/api/project_branches/rename" -d "name=main&project=${{ github.event.repository.name }}"

  create_ecr_repo:
    runs-on: basic-platform
    env:
      REGION: eu-west-1
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.5.8
        with:
          aws-access-key-id: ${{ secrets.TOOLING_ACC_AWS_ID }}
          aws-secret-access-key: ${{ secrets.TOOLING_ACC_AWS_SECRET }}
          aws-region: ${{ env.REGION }}

      - name: Provision ECR repo
        run: |
          aws servicecatalog provision-product \
          --provisioned-product-name ${{ github.event.repository.name }}-ecr-repo \
          --provisioning-artifact-name Default \
          --provisioning-parameters '[{"Key": "RepositoryName", "Value": "${{ github.event.repository.name }}"}, {"Key": "CrossAccountAccess", "Value": "enabled"}]' \
          --product-name ECR-Repo \
          --tags '[{"Key": "VantaOwner", "Value": "atul.sharma@peak.ai"}, {"Key": "VantaDescription", "Value": "PeakAI-Infrastructure"},{"Key": "VantaNonProd", "Value": "false"}]'
